### ISSUE TITLE
DNS Issue when running as docker service

### ISSUE THREAD

**Issue by daves125125** [opinari/onthefence-infrastructure#38]
core@ip-10-0-1-250 ~ $ dl -f 89
Testing some connectivity by DNS
--2017-02-08 23:14:15--  https://google.com/
Testing some connectivity by IP
Resolving google.com... failed: Try again.
wget: unable to resolve host address 'google.com'
--2017-02-08 23:14:20--  http://209.85.202.139/
Connecting to 209.85.202.139:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2017-02-08 23:14:20--  http://www.google.com/
Done...
Cert Type: full-ssl-certs
Restoring SSL Certs....
   ____        _      __   __         
  / __/______ (_)__ _/ /  / /____ ____
 / _// __/ -_) / _ `/ _ \/ __/ -_) __/
/_/ /_/  \__/_/\_, /_//_/\__/\__/_/   
              /___/                   v0.2.1
2017/02/08 23:14:25 Performing Restore
2017/02/08 23:14:25 Downloading file from: '/full-ssl-certs.tar.gz' to: '/etc/ssl'
Resolving www.google.com... failed: Try again.
wget: unable to resolve host address 'www.google.com'
2017/02/08 23:14:46 Error executing download request: Post https://content.dropboxapi.com/2/files/download: dial tcp: lookup content.dropboxapi.com on 127.0.0.11:53: read udp 127.0.0.1:47510->127.0.0.11:53: i/o timeout
Restored SSL Backup!

**Comment by daves125125** [comment]
This is due to the fact that Docker uses embedded DNS. When a user defined network is used it will resolve using Docker's DNS to resolve service names etc. When these don't resolve / match (for example an attempt to resolve an external domain e.g. https://api.dropbox.com... etc) it will look to the /etc/resolve file on the host which the docker daemon is running.

For DigitalOcean the resolve file has the following:

8.8.8.8 
8.8.4.4
which are googles public DNS nameserver.

For EC2 this is a local IP (subnet), e.g. 10.0.0.2 hence it cant resolve the Domain and download the file.

**Comment by daves125125** [comment]
Possible Solutions:

- Docker 1.13 has --dns support for docker services
- Manipulating the /etc/resolve file on EC2 hosts (use google's DNS?)
- Use a different base image for nginx (we don't see this issue on Debian based images or older redis-3.2 alpine variants, so these may use different /etc/host or /etc/resolve configurations AND / OR the nginx alpine base image configuration is interfering).

**Comment by daves125125** [comment]
Issue was overlapping subnets - aws vpc and edge network

**Comment by zyndaras** [comment]
Writing this in case we ever need to revisit this if DO also clashes... 
Docker network assigned the 10.0.0.0/24 subnet to edge (being the first network without an explicitly defined subnet like consul). 
This conflicts, somehow, with AWS vpc
